package com.api.soap.client.ZFM_IF_SD_DELIVERY_O2O;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * 
 *       
 *
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-19T16:37:57.510+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:rfc:functions", name = "ZFM_IF_SD_DELIVERY_O2O")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFMIFSDDELIVERYO2O {

    @WebMethod(operationName = "ZFM_IF_SD_DELIVERY_O2O", action = "urn:sap-com:document:sap:rfc:functions:ZFM_IF_SD_DELIVERY_O2O:ZFM_IF_SD_DELIVERY_O2ORequest")
    @RequestWrapper(localName = "ZFM_IF_SD_DELIVERY_O2O", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.api.soap.client.ZFM_IF_SD_DELIVERY_O2O.ZFMIFSDDELIVERYO2O_Type")
    @ResponseWrapper(localName = "ZFM_IF_SD_DELIVERY_O2OResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.api.soap.client.ZFM_IF_SD_DELIVERY_O2O.ZFMIFSDDELIVERYO2OResponse")
    public void zfmIFSDDELIVERYO2O(
        @WebParam(name = "IS_HEADER", targetNamespace = "")
        com.api.soap.client.ZFM_IF_SD_DELIVERY_O2O.ZSDSZIFTG00080 isHEADER,
        @WebParam(mode = WebParam.Mode.INOUT, name = "IT_ZIFTG00080_D1", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFZIFTG00080D1> itZIFTG00080D1,
        @WebParam(mode = WebParam.Mode.INOUT, name = "IT_ZIFTG00080_D2", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFZIFTG00080D2> itZIFTG00080D2,
        @WebParam(mode = WebParam.Mode.OUT, name = "E_RETURN_DESC", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eRETURNDESC,
        @WebParam(mode = WebParam.Mode.OUT, name = "E_RETURN_FLAG", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eRETURNFLAG
    );
}
