package com.api.soap.client.ZFM_IF_SD_DELIVERY_O2O;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-19T16:37:57.543+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "ZFM_IF_SD_DELIVERY_O2O", 
                  wsdlLocation = "file:/Users/mac373/dev/J2EE/projects/sbapi/src/main/java/com/api/soap/client/wsdl/sapws.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:rfc:functions") 
public class ZFMIFSDDELIVERYO2O_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:rfc:functions", "ZFM_IF_SD_DELIVERY_O2O");
    public final static QName ZFMIFSDDELIVERYO2OSoap12 = new QName("urn:sap-com:document:sap:rfc:functions", "ZFM_IF_SD_DELIVERY_O2O_soap12");
    public final static QName ZFMIFSDDELIVERYO2O = new QName("urn:sap-com:document:sap:rfc:functions", "ZFM_IF_SD_DELIVERY_O2O");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/mac373/dev/J2EE/projects/sbapi/src/main/java/com/api/soap/client/wsdl/sapws.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZFMIFSDDELIVERYO2O_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/mac373/dev/J2EE/projects/sbapi/src/main/java/com/api/soap/client/wsdl/sapws.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZFMIFSDDELIVERYO2O_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZFMIFSDDELIVERYO2O_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZFMIFSDDELIVERYO2O_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZFMIFSDDELIVERYO2O_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZFMIFSDDELIVERYO2O_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZFMIFSDDELIVERYO2O_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZFMIFSDDELIVERYO2O
     */
    @WebEndpoint(name = "ZFM_IF_SD_DELIVERY_O2O_soap12")
    public ZFMIFSDDELIVERYO2O getZFMIFSDDELIVERYO2OSoap12() {
        return super.getPort(ZFMIFSDDELIVERYO2OSoap12, ZFMIFSDDELIVERYO2O.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFMIFSDDELIVERYO2O
     */
    @WebEndpoint(name = "ZFM_IF_SD_DELIVERY_O2O_soap12")
    public ZFMIFSDDELIVERYO2O getZFMIFSDDELIVERYO2OSoap12(WebServiceFeature... features) {
        return super.getPort(ZFMIFSDDELIVERYO2OSoap12, ZFMIFSDDELIVERYO2O.class, features);
    }


    /**
     *
     * @return
     *     returns ZFMIFSDDELIVERYO2O
     */
    @WebEndpoint(name = "ZFM_IF_SD_DELIVERY_O2O")
    public ZFMIFSDDELIVERYO2O getZFMIFSDDELIVERYO2O() {
        return super.getPort(ZFMIFSDDELIVERYO2O, ZFMIFSDDELIVERYO2O.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFMIFSDDELIVERYO2O
     */
    @WebEndpoint(name = "ZFM_IF_SD_DELIVERY_O2O")
    public ZFMIFSDDELIVERYO2O getZFMIFSDDELIVERYO2O(WebServiceFeature... features) {
        return super.getPort(ZFMIFSDDELIVERYO2O, ZFMIFSDDELIVERYO2O.class, features);
    }

}
